### ISSUE TITLE
1.0.2 version cause problems: hpos_is_enabled cannot be called statically

### ISSUE THREAD

**Issue by joniahola** [woocommerce/woocommerce-legacy-rest-api#10]
I have latest Woocommerce (8.9.0) and Legacy Rest API (1.0.2).  Php version is 8.2.

I got this problem
```
[15-May-2024 08:50:19 UTC] PHP Fatal error:  Uncaught Error: Non-static method WC_Legacy_REST_API_Plugin::hpos_is_enabled() cannot be called statically in /var/www/web/app/plugins/woocommerce-legacy-rest-api/includes/class-wc-legacy-rest-api-plugin.php:77
Stack trace:
#0 /var/www/web/app/plugins/woocommerce-legacy-rest-api/includes/class-wc-legacy-rest-api-plugin.php(28): WC_Legacy_REST_API_Plugin::maybe_add_hpos_incompatibility_admin_notice()
#1 /var/www/html/wp/wp-includes/class-wp-hook.php(324): WC_Legacy_REST_API_Plugin::on_woocommerce_init()
#2 /var/www/html/wp/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters()
#3 /var/www/html/wp/wp-includes/plugin.php(517): WP_Hook->do_action()
#4 /var/www/web/app/plugins/woocommerce/includes/class-woocommerce.php(781): do_action()
#5 /var/www/html/wp/wp-includes/class-wp-hook.php(324): WooCommerce->init()
#6 /var/www/html/wp/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters()
#7 /var/www/html/wp/wp-includes/plugin.php(517): WP_Hook->do_action()
#8 /var/www/html/wp/wp-settings.php(695): do_action()
#9 /var/www/html/wp-config.php(9): require_once('...')
#10 /var/www/html/wp/wp-load.php(55): require_once('...')
#11 /var/www/html/wp/wp-admin/admin.php(34): require_once('...')
#12 /var/www/html/wp/wp-admin/plugins.php(10): require_once('...')
#13 {main}
  thrown in /var/www/web/app/plugins/woocommerce-legacy-rest-api/includes/class-wc-legacy-rest-api-plugin.php on line 77
```

I downgrade plugin and everything work properly

**Comment by sukafia** [comment]
8193672-zen

I was just in the process of creating an issue for this.

**Comment by underthecocotree** [comment]
There is a pull request to fix this: https://github.com/woocommerce/woocommerce-legacy-rest-api/pull/11

**Comment by imodouglas** [comment]
8194046-zen

**Comment by circularcube** [comment]
Pull request #11 fixed the isse for me 👍

**Comment by Konamiman** [comment]
v1.0.3 with the fix released in both [GitHub](https://github.com/woocommerce/woocommerce-legacy-rest-api/releases/tag/1.0.3) and [the wordpress.org directory](https://wordpress.org/plugins/woocommerce-legacy-rest-api/).

**Comment by joniahola** [comment]
Worked well. Thank you for fast reply!
